jest.mock('react-native/Libraries/Animated/NativeAnimatedHelper');
jest.mock('@itour/shared', () => ({
  getColors: () => ({
    background: '#ffffff',
    foreground: '#0a0a0a',
    card: '#ffffff',
    cardForeground: '#0a0a0a',
    border: '#e5e5e5',
    primary: '#1a1a2e',
    primaryForeground: '#ffffff',
    secondary: '#f5f5f5',
    secondaryForeground: '#1a1a2e',
    muted: '#f5f5f5',
    mutedForeground: '#737373',
    destructive: '#ef4444',
    accent: '#f5f5f5',
    accentForeground: '#1a1a2e',
    input: '#e5e5e5',
    ring: '#a1a1aa',
    popover: '#ffffff',
    popoverForeground: '#0a0a0a',
  }),
  getStatusColors: () => ({
    PENDING: { bg: '#fef2f2', text: '#dc2626', border: '#fecaca' },
    ASSIGNED: { bg: '#ecfdf5', text: '#059669', border: '#a7f3d0' },
    IN_PROGRESS: { bg: '#eff6ff', text: '#2563eb', border: '#bfdbfe' },
    COMPLETED: { bg: '#f0fdf4', text: '#16a34a', border: '#bbf7d0' },
    CANCELLED: { bg: '#f4f4f5', text: '#71717a', border: '#d4d4d8' },
    NO_SHOW: { bg: '#fff7ed', text: '#ea580c', border: '#fed7aa' },
  }),
  spacing: { 0: 0, 1: 4, 2: 8, 3: 12, 4: 16, 5: 20, 6: 24, 8: 32, 10: 40, 12: 48, 16: 64 },
  borderRadius: { none: 0, sm: 4, md: 6, lg: 8, xl: 12, '2xl': 16, '3xl': 20, full: 9999 },
  typography: {
    h1: { fontSize: 32, fontWeight: '700' },
    h2: { fontSize: 24, fontWeight: '700' },
    h3: { fontSize: 20, fontWeight: '600' },
    h4: { fontSize: 18, fontWeight: '600' },
    body: { fontSize: 16, fontWeight: '400' },
    bodyMedium: { fontSize: 16, fontWeight: '500' },
    bodySm: { fontSize: 14, fontWeight: '400' },
    bodySmMedium: { fontSize: 14, fontWeight: '500' },
    caption: { fontSize: 12, fontWeight: '400' },
    captionMedium: { fontSize: 12, fontWeight: '500' },
    label: { fontSize: 14, fontWeight: '600' },
    button: { fontSize: 16, fontWeight: '600' },
    buttonSm: { fontSize: 14, fontWeight: '600' },
  },
  serviceTypeColors: {
    ARR: { bg: '#DBEAFE', text: '#1D4ED8' },
    DEP: { bg: '#FEE2E2', text: '#DC2626' },
    EXCURSION: { bg: '#D1FAE5', text: '#059669' },
    ROUND_TRIP: { bg: '#EDE9FE', text: '#7C3AED' },
    ONE_WAY_GOING: { bg: '#FEF3C7', text: '#D97706' },
    ONE_WAY_RETURN: { bg: '#FFE4E6', text: '#E11D48' },
    OVER_DAY: { bg: '#CFFAFE', text: '#0891B2' },
    TRANSFER: { bg: '#E0E7FF', text: '#4338CA' },
    CITY_TOUR: { bg: '#FCE7F3', text: '#DB2777' },
    COLLECTING_ONE_WAY: { bg: '#FEF9C3', text: '#CA8A04' },
    COLLECTING_ROUND_TRIP: { bg: '#ECFCCB', text: '#65A30D' },
    EXPRESS_SHOPPING: { bg: '#F3E8FF', text: '#9333EA' },
  },
  useNetwork: () => ({ isOnline: true }),
  formatDate: (d: string) => d,
  formatTime: (t: string) => t,
  formatCurrency: (a: number, c: string) => `${a} ${c}`,
  today: () => '2026-02-20',
  addDays: (dateStr: string, days: number) => {
    const d = new Date(dateStr + 'T00:00:00');
    d.setDate(d.getDate() + days);
    return d.toISOString().split('T')[0];
  },
  getOriginLabel: () => 'Cairo Airport (CAI)',
  getDestinationLabel: () => 'Sharm El Sheikh',
  getRouteLabel: (job: any) => 'Cairo Airport (CAI) \u2192 Sharm El Sheikh',
  useT: () => (key: string) => key,
  t: (key: string) => key,
}));
